### ISSUE TITLE
libc6

### ISSUE THREAD

**Issue by cslamo** [dutilh/CAT#1]
I get an error stemming from a wrong version of libc6. It requires compiling the executables on my system, as I'm using an academic cluster and its OS can't be upgraded right now. Can you post instructions and the source files to do my own compilation?
Thanks

**Comment by diegocambuy** [comment]
Hello Claudio.

Can you tell me when did you download it while I check on that?

Thank you

Em terça-feira, 6 de setembro de 2016, Claudio Slamovits <
notifications@github.com> escreveu:

**Comment by cslamo** [comment]
Hi Diego,

It was last week, Friday I think.

Claudio
On Sep 6, 2016, at 9:37 AM, diegocambuy <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello Claudio.

Can you tell me when did you download it while I check on that?

Thank you

Em terça-feira, 6 de setembro de 2016, Claudio Slamovits <
notifications@github.com<mailto:notifications@github.com>> escreveu:

**Comment by diegocambuy** [comment]
Ok.
Can you please try downloading it again.
There was indeed errors which I corrected yesterday.

If error persists let me know.

Em terça-feira, 6 de setembro de 2016, Claudio Slamovits <
notifications@github.com> escreveu:

> Hi Diego,
>
> It was last week, Friday I think.
>
> Claudio
> On Sep 6, 2016, at 9:37 AM, diegocambuy <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');><mailto:
> notifications@github.com

**Comment by cslamo** [comment]
It run a bit longer this time, but produced an error. I’m attaching both ‘o’ and ‘e’ output files for you to look at. The run produced an empty scaffolds.fasta_contigs_prodigal.faa

Claudio

**Comment by diegocambuy** [comment]
how did you run it?


python cat.py scaffolds.fasta


Is prodigal in your documentation folder?
Also diamond and the other files?

If you run produced an empty faa file this means prodigal predicted 0 genes
in your scaffolds. How is your assembly?



2016-09-06 15:57 GMT+02:00 Claudio Slamovits <notifications@github.com>:

**Comment by cslamo** [comment]
Now I ran it with a good assembly of a bacterial genome, so that should be good.

I did python cat.py my_assembly.fna

Still get the errors and an empty faa file. I attach the content of documentation and the two new output files

**Comment by diegocambuy** [comment]
Yes. It should work.

There is a step where an empty faa file is created, later, this file
changes to the faa file with the proteins. Do you have permission to
write/change files in the cluster you are running?


Is the error you`re getting still "wrong version of lib6"? or a different
one?



Where are the attached files? I can`t find them.




2016-09-06 17:10 GMT+02:00 Claudio Slamovits <notifications@github.com>:

**Comment by cslamo** [comment]
Sorry, I replied via email. They are here now.
![cat_documentation](https://cloud.githubusercontent.com/assets/2362628/18279856/5794031e-742d-11e6-9590-784c7e829a9c.png)


[CATshort.sh.e6635243.txt](https://github.com/diegocambuy/CAT/files/457069/CATshort.sh.e6635243.txt)
[CATshort.sh.o6635243.txt](https://github.com/diegocambuy/CAT/files/457068/CATshort.sh.o6635243.txt)

**Comment by diegocambuy** [comment]
OK.

So as you suspected ,  prodigal requires a different version of the libc6
you have:

https://github.com/hyattpd/Prodigal/issues/14


here is the source for the files so you can do your own compilation:

Prodigal:

https://github.com/hyattpd/prodigal/releases/

Diamond:

https://github.com/bbuchfink/diamond


as for the instructions on how to do it I will look it up for you, and get
back to you as soon as possible.




2016-09-06 17:28 GMT+02:00 Claudio Slamovits <notifications@github.com>:

**Comment by cslamo** [comment]
Tried compiling Prodigal but it seems I need to ask the administrator do it (install: cannot change permissions of `/usr/local/bin': Operation not permitted).

**Comment by diegocambuy** [comment]
what I can recommend is :

try to run prodigal in a machine where you have access to any privilege you
need.
name the outpufiles by adding : "_contigs_prodigal.faa" for the faa file
and "_contigs_prodigal.gff"
, for the gff file.
so I guess in your case they are gonna be called
scaffolds.fasta_contigs_prodigal.faa and
scaffolds.fasta_contigs_prodigal.gff.

so your command should look something like this:

./prodigal.linux  -q -a  scaffolds.fasta_contigs_prodigal.faa  -f gff -i
scaffolds.fasta  -d   scaffolds.fasta_contigs_prodigal.fna  -o
scaffolds.fasta_contigs_prodigal.gff


Open cat.py

and add a hash before the lines 55 and 61

so they will be:


#os.system(faa_creator)

#os.system(prodigal)


save it and run it normally.


python cat.py scaffolds.fasta







2016-09-07 17:07 GMT+02:00 Claudio Slamovits <notifications@github.com>:

**Comment by cslamo** [comment]
Thanks, now it runs. How long does it take the blast part? So far it produced the CDS files (faa, fna), the gff and an empty daa file. No tab whatsoever.

**Comment by diegocambuy** [comment]
Is it on your screen "running diamond"?
The blast part can take long. That's gonna depend on how much sequences you
have.
Diamond is 20 000 times faster than a regular blast, so that's the fast you
can get.

After that step is over, daa file will be filled with data (binary file)
and this will be converted to a blast table m8.

They tables with the classification might appear 5 minutes after blast
search is over.

Em quarta-feira, 7 de setembro de 2016, Claudio Slamovits <
notifications@github.com> escreveu:

**Comment by cslamo** [comment]
Definitely is not going beyond generating the cds files. The run finished long ago, I checked and nothing is running for my user id. The output file and the errors file for the queue job are empty, so is the daa file and there is no blast table. What should I look at?

**Comment by diegocambuy** [comment]
Can you make me a log file of  what is being printed on the screen?
because it is impossible for the run to continue without a blast table
file. and that one is impossible to be generated without data on the daa
file.

I need to know what errors you are finding.


2016-09-09 16:53 GMT+02:00 Claudio Slamovits <notifications@github.com>:
