### ISSUE TITLE
Please use proper shebang line in Python3 script

### ISSUE THREAD

**Issue by tillea** [dutilh/CAT#103]
Hi,
thanks for releasing version 5.3 of CAT.  In the Debian packaged version of version 5.2.3 we used a patch to fix the shebang line of `CAT_pack/check.py` to make sure it will reliably work.  Sorry for not forwarding this patch.  Since the issue persists also in the latest version It would be great if you could please fix the shebang line like this:

    --- a/CAT_pack/check.py
    +++ b/CAT_pack/check.py
    @@ -1,4 +1,4 @@
    - #!/usr/bin/env/ python3
    +#!/usr/bin/env python3
    
     import hashlib
     import os

(Its basically removing the ending `'/'` after the `env` command and also shebang should not have a leading space.)

Thanks a lot
      Andreas.

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Andreas,

Thanks for bringing this to our attention! I've added the patch!

Bastiaan
