### ISSUE TITLE
LCA biased by huge number of diamond hits

### ISSUE THREAD

**Issue by tsciow** [dutilh/CAT#16]
Hi Bas,
first of all: thank you very much for this nice piece of software.
I ran into some minor problems with my data running CAT.

When I run CAT on the attached TSC* files, diamond gives me > 30.000 valid hits for my one sequence.
A quick blast search shows, that the first 100 hits are against Archaea, so it's pretty safe to say that the sequence is of archaeal origin.
CAT gives me "root" as LCA though.

I assume this is due to the large number of valid hits ( and that only one among them needs to be non-archaeal to "mess up" the LCA assignment) .
 
Maybe a quick workaround could be to limit the diamond output to an absolute number of valid hits instead of using --top, or maybe just to increase --top (to maybe 75 or something).
(--max-target-seqs (-k) maximum number of target sequences to report alignments for
--top                  report alignments within this percentage range of top alignment score (overrides --max-target-seqs). 

Any hints on which of these approaches you'd consider more suitable would be greatly appreciated (before I run diamond again on the complete dataset - I just grep-ed for one example sequence here).

Thanks a lot,
with my best wishes
Thomas

[CAT_TSC.contig2classification.txt](https://github.com/dutilh/CAT/files/2765570/CAT_TSC.contig2classification.txt)
[CAT_TSC.log](https://github.com/dutilh/CAT/files/2765571/CAT_TSC.log)
[CAT_TSC.ORF2LCA.txt](https://github.com/dutilh/CAT/files/2765572/CAT_TSC.ORF2LCA.txt)

[TSC.contig.fna.txt](https://github.com/dutilh/CAT/files/2765574/TSC.contig.fna.txt)
[TSC.predicted_protein.faa.txt](https://github.com/dutilh/CAT/files/2765575/TSC.predicted_protein.faa.txt)

**Comment by tsciow** [comment]
Hi Bastiaan,

thanks a lot for the quick reply!

> The current implementation of CAT allows you to just do that, namely change the value of the '--top' parameter. The equivalent CAT parameter is '-r' or '--range', whose default value is 10, which means only hits within 10% of the best-hit bit-score are included in the final calculations.
> 
> Thus, by default even though hits within 50% of the best-hit bit-score are saved to the Diamond file, only the top 10% are considered by CAT. We do it like this so that you only have to run Diamond once, and from then on can experiment with different values of the '-r' parameter, up to 50%.
> 
> In your case this means that decreasing '-r' to e.g. 5 would narrow down the classification of the individual ORFs.
> 

Sounds great! Very nice you thought of this option!
This should do the trick!

It looks like I really got the worst possible example sequence here.
Even going down to -r 1 only gave me "cellular organism" as LCA.
Going down to 0.5 (had to comment out the "choices" part in the code so CAT would accept float values) finally gave me Archaea (which is what I expected and what makes sense) - of course -r 0.5 isn't a reasonable value for the other ORFs in my Metagenome. 

I guess I'll need to identify that one hit that lacks decent tax. info and messes up the LCA annotation.
Or maybe I'll loop and grep through my diamond result files to limit them to the top 100 hits for each query. But that sure is nothing you need to worry about ;).


Thanks again for all your help,
keep up the great work,

Best wishes,
Thomas




> I hope this answer your question, please let me know if you have additional questions!
> 
> Best wishes,
> 
> Bastiaan

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Thomas,

Just as a little update: we have put a preprint online at https://www.biorxiv.org/content/10.1101/530188v1, where you can see the trade-off of the parameters used! Will update the manual soon as well.

Best wishes,

bastiaan
