### ISSUE TITLE
Incompatible Diamond Version

### ISSUE THREAD

**Issue by jeffkimbrel** [dutilh/CAT#19]
Hello,

I'm getting problem similar to #4 using the downloaded CAT databases (2018-12-12).

```
Error: Database was built with a different version of Diamond and is incompatible.
[2019-03-11 23:37:55.541631] ERROR: Diamond finished abnormally.
```

I'm running Diamond v0.9.21.122, and installed everything from bioconda, which should have compatible Diamond versions. Which version of diamond was the 2018-12-12 CAT database built with?

```
$ CAT -v
CAT v4.3.3 (December 14, 2018) by F. A. Bastiaan von Meijenfeldt.
```

Jeff

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Jeff,

Yes, this is a known problem with Diamond. The 2018 database was build with Diamond v0.9.14.
For now, the 20190108 database (http://tbb.bio.uu.nl/bastiaan/CAT_prepare/CAT_prepare_20190108.tar.gz) is compatible with your (and the bioconda) version of Diamond. I'm thinking of more viable solution to having different versions of the databases online.

Hope this helps for you, let me know if you have further questions!

**Comment by jeffkimbrel** [comment]
Thanks for the help. Rather than re-download the rather large reference database, I just downgraded by Diamond install to v0.9.14, and CAT now works.

Thanks again,

Jeff

**Comment by bastiaanvonmeijenfeldt** [comment]
Great! Let me know if you have other questions!

Bastiaan

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Menia,

What database version did you download? Within the database folder there is a file called {DATE}.CAT_prepare.fresh.log, which shows the DIAMOND version that was used for the database construction! For example, in the 20190719 version of the database files, you'll find:

[2019-07-19 19:42:52.803479] DIAMOND found: diamond version 0.9.21.

We are still thinking of making this a little easier (supplying a version of DIAMOND ourselves for example). For now, I hope this helps!

Best wishes,

Bastiaan

**Comment by gavri003** [comment]
Hi Bastiaan,

I installed diamond version 0.9.21 and it worked.

Thanks for your fast response.

Cheers!
Menia
