### ISSUE TITLE
Appended '*' (asterisk) to taxonomy

### ISSUE THREAD

**Issue by samnooij** [dutilh/CAT#22]
I have only found one example and it seems random. In classifications of metagenomics contigs, I get this output:
```
$ grep "NODE_3871_" CAT.ORF2LCA.txt
NODE_3871_length_1244_cov_2.250214_1 1;10239;35237;549779;985780;1977630;1977635;1977631*    59.3
```
_(Note the asterisk appended to taxid 1977631!!)_

Then the asterisk is taken along to the other output files:
```
$ grep "NODE_3871_" contig2classification.txt
NODE_3871_length_1244_cov_2.250214      classified      1       1       1;10239;35237;549779;985780;1977630;1977635;1977631*  1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00
```
And apparently it ends up appended to the species name as well:
```
$ egrep "Catovirus CTV1\*" add_names.txt
NODE_3871_length_1244_cov_2.250214    classified      1       1       1;10239;35237;549779;985780;1977630;1977635;1977631*  1.00;1.00;1.00;1.00;1.00;1.00;1.00;1.00 Viruses: 1.00   NA      NA   NA       Mimiviridae: 1.00       Catovirus: 1.00 Catovirus CTV1*: 1.00
```
So it turns ["Catovirus CTV1"](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1977631)  into "Catovirus CTV1*".

The sequence I get this with, is:
``` 
>NODE_3871_length_1244_cov_2.250214_1 # 457 # 1242 # -1 # ID=3871_1;partial=01;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.288
DMSHAFRDAILNNLISHLNKLVNRTNDLNIFDLCGGRGGDIFKLSSLVNIKNLMVEDADK
```

_Sidenote: Pasting this sequence in [blastp](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastp&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome) returns different species._

Other contigs in the same dataset don't have this asterisk.

CAT version: 4.3.3
DIAMOND version: 0.9.14
BLAST nr database: tbb.bio.uu.nl/bastiaan/CAT_prepare/CAT_prepare_20181212.tar.gz

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Sam,

See https://github.com/dutilh/CAT#marking-suggestive-classifications-with-an-asterisk.
It's 'extra', and might be very useful to some and less so to others. If you do not like it you can just .rstrip('*') while parsing the output files.

Hope this helps!

Bastiaan
