### ISSUE TITLE
donwload of taxonomy files failed

### ISSUE THREAD

**Issue by piwling** [dutilh/CAT#25]
Hi Bastiaan，
 When I perform the command “$ CAT prepare --fresh” on Centos, the result always show that “ERROR: donwload of taxonomy files failed”.I have tried several times but it always failed. How can I deal with that? (The dependencies and database file have been exit) .

This is the entire CAT log.
(cat) [pwl@ibg pwl]$ CAT prepare --fresh
# CAT v4.3.3.
CAT prepare is running, constructing a fresh database.
Rawr!
WARNING: preparing the database files may take a couple of hours.
Supplied command: /home/xiyangd/miniconda2/envs/cat/bin/CAT prepare --fresh
Taxonomy folder: 2019-06-15_taxonomy/
Database folder: 2019-06-15_CAT_database/
Log file: 2019-06-15.CAT_prepare.fresh.log
[2019-06-15 04:38:16.966006] Diamond found: diamond version 0.9.21.
[2019-06-15 04:38:16.966592] Taxonomy folder exists already. Taxonomy files will be downloaded to it.
[2019-06-15 04:38:16.966789] Database folder exists already. Database file will be downloaded to it / constructed in it.
[2019-06-15 04:38:16.967401] Downloading and extracting taxonomy files from ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz to 2019-06-15_taxonomy.
[2019-06-15 05:25:47.875356] ERROR: donwload of taxonomy files failed._
Best ,
piwling

**Comment by bastiaanvonmeijenfeldt** [comment]
Dear Piwling,

Thanks for this bug report! Could you confirm for me that the following bash command works on your system?

`wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz`

Best wishes,

Bastiaan

**Comment by piwling** [comment]
Dear Bastiaan,
I am sorry that the computer server in my lab was broken. So I can not try that command now. When the system run normally, I will tell you the result.
Best wishes,
Piwling

**Comment by bastiaanvonmeijenfeldt** [comment]
Great, keep me updated!

**Comment by piwling** [comment]
Ok, no problem.

**Comment by piwling** [comment]
Dear Bastiaan,
I am sorry for getting back to you late. My research topic have been changed, and  I donnot need to  use CAT. Maybe it is time to close this issue. 
Best wishes,
Piwling

**Comment by bastiaanvonmeijenfeldt** [comment]
Thanks for letting me know! I'm closing this issue for now, you can reopen it if you stumble upon the problem again in the future!

**Comment by piwling** [comment]
Got it, thanks a lot.
