### ISSUE TITLE
CAT and MacOS

### ISSUE THREAD

**Issue by HadrienG** [dutilh/CAT#26]
Thank you for trying to make CAT available for MacOS users.

I've run into one _slight_ problem though, it is that, on MacOS, the most used filesystems (HFS+, and later APFS) are _case insensitive_.

A consequence of this is that terminal commands can be called both lower and uppercase.
As an example:

```bash
(metagenomics) hadrien:~/Documents/workspace/cat_test$ ls
a.txt  b.txt  hello.fasta
(metagenomics) hadrien:~/Documents/workspace/cat_test$ LS
a.txt  b.txt  hello.fasta
```

See where this is going? That's right, CAT replace the `cat` command usually used to concatenate or display the content of a file!

```bash
(metagenomics) hadrien:~/Documents/workspace/cat_test$ cat hello.fasta 
usage: CAT (prepare | contigs | bin | bins | add_names | summarise) [-v / --version] [-h / --help]
CAT: error: one of the arguments prepare contigs bin bins add_names summarise is required
(metagenomics) hadrien:~/Documents/workspace/cat_test$ CAT hello.fasta 
usage: CAT (prepare | contigs | bin | bins | add_names | summarise) [-v / --version] [-h / --help]
CAT: error: one of the arguments prepare contigs bin bins add_names summarise is required
(metagenomics) hadrien:~/Documents/workspace/cat_test$ /bin/cat hello.fasta 
>my_sequence
ATGC
```

which is highly irritating to say the least.

May I suggest to either:
- Write a big disclaimer about this in the documentation, and beg people to either not putting CAT in their PATH on MacOS, or to have a conda environment just for your tool.
- change the name of your software.

Thank you in advance.
Hadrien.

**Comment by bastiaanvonmeijenfeldt** [comment]
Dear @HadrienG ,

Thanks for reporting this! We do not extensively test on Mac OS, and I can imagine this can be obnoxious.
I have added a warning for Mac OS users to the `README.md`.

Also for documentation purposes, in case other people encounter the same problem: simply removing CAT from your `$PATH` variable again will restore the command to the standard unix `cat` utility. Just remember to restart your terminal once after removing.

Best wishes,

Bastiaan
