### ISSUE TITLE
Allowing CAT to use UniProt databases

### ISSUE THREAD

**Issue by openpaul** [dutilh/CAT#29]
I would like to use CAT with UniProts databases as they contain a more suitable set of proteins for my comparisons.
I am working on making CAT prepare work with this, but it requires a lot of manual parsing and fixing of TaxIDs to make UniProt compatible with the NCBI taxonomy. 
Is this a feature that would be interesting to have or not? If not, just close this issue again.

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @openpaul,

For now I cannot really work on this myself, but if you have a working solution that you feel is stable and is useful to people please let us know! We would be happy to implement it. Feel free to fork our repository and PR.

Bastiaan

**Comment by openpaul** [comment]
Thanks, goo to know. If I come up with something I will let you know. For now I close this issue again.
