### ISSUE TITLE
'CAT prepare --fresh' doesn't create all required files?

### ISSUE THREAD

**Issue by andrewgull** [dutilh/CAT#35]
Hi there again!
After running the following commands
```
$ CAT prepare --fresh 
$ CAT prepare --existing -d {folder containing nr} -t {folder containing taxonomy files}
```
In the log file, I see these error messages:

> [2020-03-08 16:11:11.405982] ERROR: file fastaid2LCAtaxid is not found in database folder.
[2020-03-08 16:11:11.406296] ERROR: file taxids_with_multiple_offspring not found in database folder.

So, it seems that CAT prepare doesn't create `fastaid2LCAtaxid` and `taxids_with_multiple_offspring` files?

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @andrewgull,

Could you supply the log file of `CAT prepare --fresh`?
I have updated the database files on our servers to 2020-03-04, so if you don't want to debug your setup you could also get those!

Best wishes,

Bastiaan
