### ISSUE TITLE
ERROR: DIAMOND finished abnormally

### ISSUE THREAD

**Issue by polinanvkv** [dutilh/CAT#37]
Hi there,

I am using CAT to annotate contigs and the procedure stops at using diamond with `ERROR: DIAMOND finished abnormally.` The diamond version is 0.9.21 the same as in `2020-03-04.CAT_prepare.fresh.log`. CAT was installed with Conda. Any ideas ?

**Comment by Finesim97** [comment]
Hi, 
DIAMOND should produce an error message, did you record the STDERR stream?

**Comment by polinanvkv** [comment]
Hello,
not sure what you mean so here's the full output: 

```
Supplied command: /home/users/pnovikova/miniconda3/envs/catbat/bin/CAT contigs -c /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/mgmt.assembl
y.merged.fa -d /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_CAT_database -t /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-
04_taxonomy

Contigs fasta: /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/mgmt.assembly.merged.fa

Taxonomy folder: /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_taxonomy/
Database folder: /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_CAT_database/
Parameter r: 10
Parameter f: 0.5
Log file: out.CAT.log

-----------------

Doing some pre-flight checks first.
[2020-04-20 12:32:19.830815] Prodigal found: Prodigal V2.6.3: February, 2016.
[2020-04-20 12:32:19.836541] DIAMOND found: diamond version 0.9.21.
Ready to fly!

-----------------

[2020-04-20 12:32:19.837798] Importing contig names from /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/mgmt.assembly.merged.fa.
[2020-04-20 12:32:21.528245] Running Prodigal for ORF prediction. Files out.CAT.predicted_proteins.faa and out.CAT.predicted_proteins.gff will be generated. Do no
t forget to cite Prodigal when using CAT or BAT in your publication!
```

**Comment by Finesim97** [comment]
Hi,
Can you change the file `/home/users/pnovikova/miniconda3/envs/catbat/share/cat-5.0.4-0/CAT_pack/contigs.py` and remove the `--quiet`:

https://github.com/dutilh/CAT/blob/48282a978ec965c37b1e688816f73fcaa0caa2ed/CAT_pack/shared.py#L115

And then save the entire output:

``` sh
CAT contigs -c /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/mgmt.assembly.merged.fa -d  /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_CAT_database -t /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_taxonomy &> run.log
```

`run.log` now should contain DIAMOND output.

**Comment by polinanvkv** [comment]
Lukas,
can you pls specify whether you mean to change `shared.py` or `contigs.py`?

**Comment by Finesim97** [comment]
I meant shared, sry.

**Comment by polinanvkv** [comment]
Ok, this is what I get: 

```
diamond v0.9.21.122 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 28
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: ./
Opening the database...  [0.019375s]
Percentage range of top alignment score to report hits: 50
Opening the input file...  [6.7e-05s]
Opening the output file...  [0.00013s]
Loading query sequences...  [0.769291s]
Masking queries...  [18.7994s]
Building query seed set...  [0.030655s]
Algorithm: Double-indexed

Building query histograms...  [1.34526s]
Allocating buffers...  [0.000506s]
Loading reference sequences...  [10.3957s]
Building reference histograms...  [32.9307s]
Allocating buffers...  [7.8e-05s]
Initializing temporary storage...  [0.243595s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index... [2020-04-20 17:47:10.043610] ERROR: DIAMOND finished abnormally.
# CAT v5.0.4.

CAT is running. Protein prediction, alignment, and contig classification are carried out.
Rarw!

Supplied command: /home/users/pnovikova/miniconda3/envs/catbat/bin/CAT contigs -c /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/mgmt.assembl
y.merged.fa -d /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_CAT_database -t /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-
04_taxonomy

Contigs fasta: /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/mgmt.assembly.merged.fa
Taxonomy folder: /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_taxonomy/
Database folder: /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_CAT_database/
Parameter r: 10
Parameter f: 0.5
Log file: out.CAT.log

-----------------

Doing some pre-flight checks first.

[2020-04-20 17:26:27.660179] Prodigal found: Prodigal V2.6.3: February, 2016.
[2020-04-20 17:26:27.666428] DIAMOND found: diamond version 0.9.21.
Ready to fly!

-----------------

[2020-04-20 17:26:27.667481] Importing contig names from /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/mgmt.assembly.merged.fa.
[2020-04-20 17:26:29.380648] Running Prodigal for ORF prediction. Files out.CAT.predicted_proteins.faa and out.CAT.predicted_proteins.gff will be generated. Do no
t forget to cite Prodigal when using CAT or BAT in your publication!
[2020-04-20 17:45:57.568141] ORF prediction done!
[2020-04-20 17:45:57.568441] Parsing ORF file out.CAT.predicted_proteins.faa
[2020-04-20 17:45:59.364187] Homology search with DIAMOND is starting. Please be patient. Do not forget to cite DIAMOND when using CAT or BAT in your publication!
                                query: out.CAT.predicted_proteins.faa
                                database: /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_CAT_database/2020-03-04.nr.dmnd
                                mode: fast
                                number of cores: 28
                                block-size (billions of letters): 2.0
                                index-chunks: 4
                                tmpdir: ./
                                top: 50
```

**Comment by Finesim97** [comment]
Ok, it just dies during reference construction. I once saw something similar when working with a broken reference. I only have my own build right now, so can't give you an exact size or MD5 checksum of the .dmnd file. Could you try it with the old reference, just for comparison:
https://tbb.bio.uu.nl/bastiaan/CAT_prepare/CAT_prepare_20190719.tar.gz

**Comment by Finesim97** [comment]
You could also try my current file:
https://finesim97-public.s3.eu-central-1.amazonaws.com/KnuttReads2Bins/reference_data/CATBAT/2020-04-08.nr.dmnd
https://finesim97-public.s3.eu-central-1.amazonaws.com/KnuttReads2Bins/reference_data/CATBAT/2020-04-08.nr.fastaid2LCAtaxid
https://finesim97-public.s3.eu-central-1.amazonaws.com/KnuttReads2Bins/reference_data/CATBAT/2020-04-08.nr.taxids_with_multiple_offspring

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @Finesim97 and @polinanvkv ,

I have checked whether CAT runs on one of my own contig sets with the db and dependencies that are mentioned here. It seems to run fine on our systems, so we'll need to debug this a llittle further.

I normally only put the md5sums online for the tarball to see if your download was correct, they are in https://tbb.bio.uu.nl/bastiaan/CAT_prepare/ as well, in this case:

**1548a232a99130341b52e50e07b030fb**  CAT_prepare_20200304.tar.gz.

The md5sum of the DIAMOND database file (`.dmnd`) is:

**b0e1464addc92497536e59ec7eae93ec**  2020-03-04.nr.dmnd

@polinanvkv, could you check whether they are the same with:

`$ md5sum 2020-03-04_CAT_database/2020-03-04.nr.dmnd`?

Best wishes,

Bastiaan

**Comment by polinanvkv** [comment]
> Could you try it with the old reference, just for comparison:
> https://tbb.bio.uu.nl/bastiaan/CAT_prepare/CAT_prepare_20190719.tar.gz

Lukas, I tried the old version, I got the same output.

**Comment by polinanvkv** [comment]
@bastiaanvonmeijenfeldt 
Looks like md6sum is the same:
`b0e1464addc92497536e59ec7eae93ec  2020-03-04.nr.dmnd`

**Comment by Finesim97** [comment]
May I ask how much RAM you have (`free -h`), diskspace (`df -h .`) and whether your home folder is on a NFS?

**Comment by polinanvkv** [comment]
@Finesim97 , 
```
free -h
              total        used        free      shared  buff/cache   available
Mem:           125G         15G         35G         42M         73G        109G
Swap:          4.0G        3.6G        383M
```
and 
```
Filesystem      Size  Used Avail Use% Mounted on
irisgpfs        1.5P  698T  828T  46% /mnt/irisgpfs
```

**Comment by polinanvkv** [comment]
And if I set `-n 8` the procedure again stops at executing diamond.

**Comment by Finesim97** [comment]
Ok, sry that this has just become a throwing spaghetti at the wall process, but have you tried a newer DIAMOND version?
`conda install -c conda-forge -c bioconda diamond=0.9.29`

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @polinanvkv,

I see that you're running CAT on a cluster, which *may* be the culprit. By default the DIAMOND temporary directory is the same as the output directory, are you allowed to write large files to that location?

You can change this directory with the `--tmpdir` flag in CAT. One debug option is to set it to `/dev/shm` which will instead load the tmp files in memory (make sure it's empty afterwards or your sys admins will be unhappy!).

You'll need lots of memory so it's not a full solution but let's first see if you get past this error and next how we can solve it.

**Comment by bastiaanvonmeijenfeldt** [comment]
Also, to verify that your version of DIAMOND is indeed correct, I've put mine (0.9.21) on http://tbb.bio.uu.nl/bastiaan/CAT_prepare/Diamond_0.9.21.tar.gz. You can download it and try again, just to be sure!

**Comment by polinanvkv** [comment]
Hi @bastiaanvonmeijenfeldt , 
I run CAT specifying `--tmpdir` and it sort of worked. It worked much longer than before (9-10 h) and as a resulted produced these files:  
```
122G Apr 25 08:50 out.CAT.alignment.diamond
2.2K Apr 25 08:50 out.CAT.log
150M Apr 24 22:34 out.CAT.predicted_proteins.faa
208M Apr 24 22:34 out.CAT.predicted_proteins.gff  
```

Though the process wasn't interrupted, in the log file, I see minor errors associated with diamond: 
```
...
Deallocating reference...  [0.062512s]
Loading reference sequences...  [0.000325s]
Deallocating buffers...  [0.019574s]
Joining output blocks... Disk quota exceeded
Error: Error writing file out.CAT.alignment.diamond
terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file out.CAT.alignment.diamond
[2020-04-25 08:50:38.137255] ERROR: DIAMOND finished abnormally.

# CAT v5.0.4.

CAT is running. Protein prediction, alignment, and contig classification are carried out.
Rarw!
Supplied command: /home/users/pnovikova/miniconda3/envs/catbat/bin/CAT contigs -c /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/mgmt.assembl
y.merged.fa -d /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-04_CAT_database -t /scratch/users/pnovikova/tools/cat/CAT_prepare_20200304/2020-03-
04_taxonomy -n 8 --tmpdir /scratch/users/pnovikova/tools/cat/diamond.temp
...
```

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @polinanvkv,

It seems that indeed for some reason you cannot write temporary files to the output dir on your cluster. There appears to be a quotum for the max size of output storage or max amount of files per user.

I think it would be a good idea to ask the system administrator of your cluster what's going on here (you can probably show him/her this thread).

Moreover, we can try to decrease the size of the DIAMOND output file. For general tips and tricks see [here](https://github.com/dutilh/CAT#optimising-running-time-ram-and-disk-usage). By far the most efficient way to reduce the output file size is by setting the `--top` parameter. While doing so it's important that you realise that this might have some downstream effects, see [here](https://github.com/dutilh/CAT#setting-the-diamond---top-parameter). However if you do not plan to increase the *r* parameter later, you can safely set `--top 11` for example! An added benefit is that your run will be much faster.

Bastiaan

**Comment by ZhangDengwei** [comment]
Hi,

I got the same ERROR, and diamond still failed though I added `--tmpdir`, the following is the log.
```
Doing some pre-flight checks first.
[2020-05-29 22:33:43.463016] Prodigal found: Prodigal V2.6.3: February, 2016.
[2020-05-29 22:33:43.471114] DIAMOND found: diamond version 0.9.14.
Ready to fly!

-----------------

[2020-05-29 22:33:43.471471] Importing contig names from /mnt/microbio_research/dengwei/20200311_FMT/11.Genome_assembly/M1/contig.fa.
[2020-05-29 22:33:49.084804] Running Prodigal for ORF prediction. Files M1.predicted_proteins.faa and M1.predicted_proteins.gff will be generated. Do not forget to cite Prodigal when using CAT or BAT in your publication!
[2020-05-29 23:16:12.510148] ORF prediction done!
[2020-05-29 23:16:12.510477] Parsing ORF file M1.predicted_proteins.faa
[2020-05-29 23:16:13.481693] Homology search with DIAMOND is starting. Please be patient. Do not forget to cite DIAMOND when using CAT or BAT in your publication!
                                query: M1.predicted_proteins.faa
                                database: /home/dengwei/database/CAT/CAT_prepare_20200304/2020-03-04_CAT_database/2020-03-04.nr.dmnd
                                mode: fast
                                number of cores: 8
                                block-size (billions of letters): 2.0
                                index-chunks: 4
                                tmpdir: ./temp
                                top: 50
[2020-05-29 23:16:13.493182] ERROR: DIAMOND finished abnormally.
```
And my RAM and disk space are:
```
              total        used        free      shared  buff/cache   available
Mem:           245G        661M        111G        4.2M        133G        242G
Swap:          2.0G        228M        1.8G
```
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2      1007G  817G  145G  85% /
```
I performed it on cluster as well, so this kind of error was, in essence, derived from the computer cluster?

**Comment by Finesim97** [comment]
Hi,
Hope I can help you with your problem, do you have some more info:
1. Your home directory really is on `/dev/sda2`? That seems to be a normal drive, not a network mounted one?
2. Have you tried a more recent DIAMOND version, as stated above, the database was created with 0.9.21
3. Can you please change the `shared.py` and remove the quiet flag to diamond:
`CONDAENVHERE/share/cat-5.0.4-0/CAT_pack/contigs.py`: https://github.com/dutilh/CAT/blob/48282a978ec965c37b1e688816f73fcaa0caa2ed/CAT_pack/shared.py#L115
And save the entire output to a logfile and post it here?
4. You are running the latest version?

Write me, if you need assistance with any of these steps.

@bastiaanvonmeijenfeldt 
Can I add an verbose (-v) flag to the commands, which will for now only disable the quiet behavior or even make DIAMOND verbose?

Have a nice day,
Lukas Jansen

**Comment by ZhangDengwei** [comment]
Thanks @Finesim97 . I addressed it by updating DIAMOND from 0.9.14 to 0.9.26.

**Comment by bastiaanvonmeijenfeldt** [comment]
@Finesim97,

Yes, a -v / --verbose flag would be useful! Please do. :)

Bastiaan

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @Finesim97,

We plan on adding other aligners to CAT/BAT. To prepare for this I may change the parser code in the next couple of days. So it might be a good idea to wait a bit with the addition of the --verbose flag, if I do make changes I will add it!

Bastiaan

**Comment by bastiaanvonmeijenfeldt** [comment]
@Finesim97,

CAT and BAT now have a `--verbose` flag. It currently does not do much, except making DIAMOND verbose and printing all arguments that are supplied by the user. We will expand based on the common issues that we encounter!

Bastiaan

**Comment by jiaojiaoguan** [comment]
> 

hi,

did you mean `./CAT_pack/CAT contigs -c "/home/jiaojiao/cat/test.fasta" -d /home/jiaojiao/cat/CAT_prepare_20210107/2021-01-07_CAT_database/ -t /home/jiaojiao/cat/CAT_prepare_20210107/2021-01-07_taxonomy/  --force --tmpdir /dev/shm
`？ I add the `--tmpdir` ，but I got another error `UnboundLocalError: local variable 'log_file' referenced before assignment`.
Did you have some ideas to solve the problem?

Thank you very much!
