### ISSUE TITLE
diamond version

### ISSUE THREAD

**Issue by danshu** [dutilh/CAT#4]
Hi,

May I know which diamond version is used? I just tried to use the nr database created under documentation directory using the latest diamond verison but failed with this error:
"Error: Incompatible database version".

Best,
Quan

**Comment by kseniaarkhipova** [comment]
Hi Quan,
Usually this problem occurs when you built diamond database with previous version of diamond and is trying to make an alignment with a newer version. Is this your case? CAT was developed and tested with diamond v0.8.31.

**Comment by danshu** [comment]
Thanks!

**Comment by jeffkimbrel** [comment]
Hello,

I'm getting this same problem now with the downloaded CAT databases (2018-12-12).

```
Error: Database was built with a different version of Diamond and is incompatible.
[2019-03-11 23:37:55.541631] ERROR: Diamond finished abnormally.
```

I'm running Diamond v0.9.21.122, and installed everything from bioconda, which should have compatible Diamond versions. Which version of diamond was the 2018-12-12 CAT database built with?

Jeff
