### ISSUE TITLE
what does no support mean?

### ISSUE THREAD

**Issue by smb20200615** [dutilh/CAT#48]
Hello,

Thank you so much for your wonderful tool. I was wondering, what does it mean when it says "no support" for a species CAT annotation? Also, sometimes there is a numeric value for support. Should we filter based on that value?

Best wishes,

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @smb20200615,

Thanks for your question!

'no support' means that there is no classification on that rank that reaches the fraction of bitscore support (as chosen by the _f_ parameter). The numerical support values at the ranks that do get classifications indicate this bitscore support. For example, if support is 0.8, this means that 80% of the contig / bin supports this classification (in terms of bitscore). It is therefore very trustworty. However, if support for any classification on a certain rank is not higher than 0.1, and _f_ was set to 0.5, this rank will be marked as 'no support'.

You can filter based on these values depending on your research question, either by doing it manually or setting the _f_ parameter. The default (0.5 for CAT and 0.3 for BAT) are pretty conservative, so you can set _f_ to lower values to get more suggestive classifications. What will happen if _f_ is set below 0.5 is that sometimes a contig or bin may have multiple classifications (for example, both 0.4). What I do often myself is set _f_ to low values to get every taxonomic signal, and than filter manually.

One other tip is that in `add_names` you can set `--exclude_scores` to remove the scores from the classifications if that helps with parsing the results!

Hope this helps, best wishes,

Bastiaan

**Comment by smb20200615** [comment]
Thank you so much for your comprehensive and prompt answer. Also, I was wondering if it is ok if we assign the bin the majority classification for the contigs in that bin instead of running BAT. Thank you again!

**Comment by bastiaanvonmeijenfeldt** [comment]
The BAT classification of a bin and CAT classifications of individual contigs are not always the same. For example, you could have a bin that contains one very long contig that represents 90% of the bin that is classified as _B. fragilis_, and a lot of short contigs that all have a different classification (say _E. coli_). The BAT classification would correctly be _B. fragilis_, but the majority of contigs would be classified as _E. coli_.

What I often do is run both CAT and BAT. BAT gives me the classification of the bin, and CAT classifications within the bin give some handles on which ones might be contamination.

Let me know if you have further questions!

Bastiaan

**Comment by smb20200615** [comment]
thank you so much for the clarification!

**Comment by smb20200615** [comment]
Apologies for bothering you again. I am currently running this command. When I run CAT bin I get an annotation for each contig rather than one for the bin. Is there anything I am doing wrong? Maybe I should be using the summarize option at the end? I am basically interested in quantifying the fraction of the genome that is contaminated so I want a taxonomy for the bin and then one for each contig.

CAT contigs -c {input.MAG} -d 2020-11-23_CAT_database/ -t 2020-11-23_taxonomy -o {params.prefix} --force

CAT bin -b {input.genome} -d 2020-11-23_CAT_database/ -t 2020-11-23_taxonomy -p {params.protein} -a {params.aln} -o {params.prefix} --force

I also sometimes get this error with CAT bin:
KeyError: 'no taxid found (WP_052044669.1)'

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @smb20200615,

If you run CAT bin you should get one classification for the bin. What is the full command you're running? (i.e. with the {params.protein} etc. replace by the actual value of the variable.) Maybe a CAT run overwrites the output files of the BAT run, this can happen since you're using the --force command.

Also, the KeyError shouldn't happen, if you run into the KeyError again, could you paste the entire log?

Bastiaan
