### ISSUE TITLE
Unknown format code 'd' in prepare.py

### ISSUE THREAD

**Issue by aline385** [dutilh/CAT#49]
Hello,
I just installed CAT via bioconda. I'm trying to generate the database from myself, by running 

$ CAT prepare --fresh

or 

$ CAT prepare --existing -d {folder containing nr} -t {folder containing taxonomy files}

In both cases, I get this error message :

 File "/home/aline/anaconda3/envs/cat_env/share/cat-5.2-0/CAT_pack/prepare.py", line 138, in memory_bottleneck
    'at least {0:,d}GB of memory is needed for the database '
ValueError: Unknown format code 'd' for object of type 'str'

the environement is ubuntu 18.04, with anaconda3 and the CAT version is v5.2 (20 November, 2020)

I really have no clue on how to solve this. Thanks in advance for your help :)

Aline

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @aline385,

Thanks for reporting this, this is a bug in v5.2! I'm solving this now, stay tuned...

Bastiaan

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @aline385,

Thanks for reporting this! This was a bug in v5.2. I've published a new version (v5.2.1) that should fix it.
Hope this helps, let me know if you have further questions!

Best wishes,

Bastiaan

**Comment by aline385** [comment]
Thank you, it's working now.
:)

Aline
