### ISSUE TITLE
addnames stops with no taxid found (HCB58249.1) in ORF2LCA file

### ISSUE THREAD

**Issue by VManning** [dutilh/CAT#52]
Hello,

I have been using CAT to assign taxonomy to individual contigs in bins. It's been going really well but I just hit a snag! I am using the ORF2LCA file to add official names and one of the output files was truncated. Standard error file says:

KeyError: 'no taxid found (HCB58249.1)'

When I compare the outputs of the ORF2LCA file and the addnames file it is clear that the program stops after it hits the row with no taxid found (HCB58249.1).

I can probably go through the remaining contigs manually but it probably needs a fix. In the meantime, can you suggest a workaround? 

Thanks and this tool has been super helpful!

Viola

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Viola,

Thanks for reporting this! Let's try to debug this.
1) What version of CAT are you running? You can check this with `CAT --version`.
2) Do you have the full error message? If Python throws a KeyError there is usually also a line number mentioned.
3) Could you also paste the row of the ORF2LCA file where it goes wrong (the one with the "no taxid found HCB58249.1" annotation)?

Bastiaan

**Comment by VManning** [comment]
Hi Bastiaan,

**The version that I am running is:** CAT v5.2.1 (6 January, 2021) by F. A. Bastiaan von Meijenfeldt.

**The error message is as follows:**
Traceback (most recent call last):
  File "/nfs1/CGRB/Trippe_Lab/CAT/CAT/CAT_pack/CAT", line 84, in <module>
    main()
  File "/nfs1/CGRB/Trippe_Lab/CAT/CAT/CAT_pack/CAT", line 70, in main
    add_names.run()
  File "/nfs1/CGRB/Trippe_Lab/CAT/CAT/CAT_pack/add_names.py", line 199, in run
    lineage, taxid2rank, taxid2name, scores)
  File "/nfs1/CGRB/Trippe_Lab/CAT/CAT/CAT_pack/tax.py", line 252, in convert_to_official_names
    lineage_ranks = [taxid2rank[taxid.rstrip('*')] for taxid in lineage]
  File "/nfs1/CGRB/Trippe_Lab/CAT/CAT/CAT_pack/tax.py", line 252, in <listcomp>
    lineage_ranks = [taxid2rank[taxid.rstrip('*')] for taxid in lineage]
KeyError: 'no taxid found (HCB58249.1)'

**The row of the ORF2LCA file:**
contig_37_193 | 033.fasta | 1 | no taxid found (HCB58249.1) | 181.8

Let me know if you would like anything else!

Thanks! V

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Viola,

Thanks! I have published a new release (v5.2.3) that has this bug fixed! You can download it and run `add_names` on your previously generated output files, they are compatible.
I'm closing this issue, let me know if you run into other problems!

Bastiaan
