### ISSUE TITLE
parameter "r" is ratio or absolute number

### ISSUE THREAD

**Issue by zhaoxvwahaha** [dutilh/CAT#53]
Hi,

If I set the Dimond parameter top =10, and r=10, how many hits will be included to do the LCA of ORF? 10 or 1?

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @zhaoxvwahaha,

Both parameters are a percentage. A `--top` of 10 means that only hits within 10% range of the best alignment score are included in the DIAMOND output file. So if the bit-score of the best hit is e.g. 100, all hits with a bitscore >= 90 are included. The `-r` parameter does the same, but after alignment while parsing the alignment file. It is meant to change the fraction of included hits without having to remake the alignment file every time again. For this reason, `-r` should always be set lower than `--top`.

Let me know if you have further questions!

Bastiaan
