### ISSUE TITLE
CAT/BAT with custom database

### ISSUE THREAD

**Issue by chassenr** [dutilh/CAT#65]
Hi,
I was wondering if there also is the option to build the CAT/BAT database from a custom genome selection (with a custom taxonomy)? I have been developing a [workflow](https://github.com/chassenr/taxdb-integration) to build a cross-domain reference genome database consisting of NCBI (eukaryotes), GTDB, and CheckV. To bring all these databases under the same taxonomic umbrella I create the taxdump from scratch with custom taxids. So far I have formatted this genome selection for kraken2 and kaiju, and I was wondering if there may also be a way to use this reference with CAT/BAT. Can you explain in more detail the requirements for the input files to prepare the CAT/BAT database? This question may also be related to #60 and #64.

Thanks a lot!

**Comment by papanikos** [comment]
Hi @chassenr 

The basic two requirements for taxonomy information for CAT would be:

* `names.dmp`: A tsv file that contains `\t` separated values (or more precisely `\t|\t` separated) for a given taxid (should be unique), its human readable name and a field with the string`scientific name`. This is what you also get from `taxdump.gz`
An example looks like this:

```
6       |       p__Aenigmatarchaeota    |               |       scientific name |
7       |       p__Aenigmatarchaeota_A  |               |       scientific name |
8       |       p__Altarchaeota |               |       scientific name |
```
 
* `nodes.dmp`: A mapping of each unique taxid (field 1 from above) to its parent node in the taxonomy tree and its rank name.
An example would look like this:
```
2       |       1       |       superkingdom    |
3       |       1       |       superkingdom    |
6       |       2       |       phylum  |
7       |       2       |       phylum  |
8       |       2       |       phylum  |

```
This is also what you get from the standard `taxdump.gz` from ncbi. 

These files should be both present in a dir. To build the database for CAT you will need to use the `CAT prepare` subcommand and provide the path to this dir via the `-t / --taxonomy_folder` argument.

**Comment by chassenr** [comment]
Thanks @papanikos for the detailed explanation. I will try it out! I am closing the issue for now. If I encounter problems when testing with my custom DB, I will re-open it.

**Comment by papanikos** [comment]
Btw, I moved the `prot.accession2taxid.FULL.gz` inside the taxonomy folder in the description above. This is where CAT expects it.

**Comment by chassenr** [comment]
Just in case this will also be helpful for others, here is the code that I used to build a CAT database for GTDB:

```
# Download protein seqs and taxonomy
cd /bio/Databases/GTDB/R202 # adjust based on your local file structure
wget https://data.gtdb.ecogenomic.org/releases/release202/202.0/genomic_files_reps/gtdb_proteins_aa_reps_r202.tar.gz
wget https://data.gtdb.ecogenomic.org/releases/release202/202.0/bac120_taxonomy_r202.tsv
wget https://data.gtdb.ecogenomic.org/releases/release202/202.0/ar122_taxonomy_r202.tsv

tar -xzvf gtdb_proteins_aa_reps_r202.tar.gz
rm gtdb_proteins_aa_reps_r202.tar.gz
cat bac120_taxonomy_r202.tsv ar122_taxonomy_r202.tsv > gtdb_taxonomy_r202.tsv

# generate nodes and names files
# see: https://github.com/rrwick/Metagenomics-Index-Correction
# I cloned this repository to /home/hassenru/Repos/
cd /bio/Databases/GTDB/R202/cat
mkdir CAT_database
mkdir CAT_taxonomy
conda activate taxonkit-0.8.0
/home/hassenru/Repos/Metagenomics-Index-Correction/tax_from_gtdb.py --gtdb ../gtdb_taxonomy_r202.tsv --nodes CAT_taxonomy/nodes.dmp --names CAT_taxonomy/names.dmp
cut -f2 ../gtdb_taxonomy_r202.tsv | uniq > tmp.tax
cut -d';' -f7 tmp.tax | sed 's/s__//' | taxonkit name2taxid --data-dir CAT_taxonomy/ | paste tmp.tax - > tmp.taxid

# concatenate protein files
# removing stop codons from annotation in case this may cause downstream incompatibility (not sure if this was really necessary, but since genbank genomes don't have * I thought removing them here might be a good idea)
find ../protein_faa_reps/archaea -name '*.faa' | parallel -j100 'sed "s/\*//g" {}' > CAT_database/gtdb_reps.nr
find ../protein_faa_reps/bacteria -name '*.faa' | parallel -j100 'sed "s/\*//g" {}' >> CAT_database/gtdb_reps.nr
gzip CAT_database/gtdb_reps.nr

# generate accession to taxid file
echo -e 'accession.version\ttaxid' > CAT_taxonomy/prot.accession2taxid.FULL
ls -1 ../protein_faa_reps/archaea/*.faa | xargs -n1 basename | sed 's/_protein\.faa//' | while read line
do
  TAXID=$(echo ${line} | grep -F -w -f - ../gtdb_taxonomy_r202.tsv | cut -f2 | grep -F -w -f - tmp.taxid | cut -f3)
  grep '^>' ../protein_faa_reps/archaea/${line}_protein.faa | sed -e 's/^>//' -e 's/ .*//' | sed "s/$/\t$TAXID/"
done >> CAT_taxonomy/prot.accession2taxid.FULL
find ../protein_faa_reps/bacteria -name '*.faa' | xargs -n1 basename | sed 's/_protein\.faa//' | while read line
do
  TAXID=$(echo ${line} | grep -F -w -f - ../gtdb_taxonomy_r202.tsv | cut -f2 | grep -F -w -f - tmp.taxid | cut -f3)
  grep '^>' ../protein_faa_reps/bacteria/${line}_protein.faa | sed -e 's/^>//' -e 's/ .*//' | sed "s/$/\t$TAXID/"
done >> CAT_taxonomy/prot.accession2taxid.FULL
gzip CAT_taxonomy/prot.accession2taxid.FULL

# build CAT DB
conda activate cat-5.2.3
CAT prepare --existing -t /bio/Databases/GTDB/R202/cat/CAT_taxonomy -d /bio/Databases/GTDB/R202/cat/CAT_database -n 100

# clean-up
rm tmp.taxid tmp.tax
```

**Comment by AstrobioMike** [comment]
This is stellar, @chassenr! Thank you so much for sharing!
