### ISSUE TITLE
No error in object file, empty output files

### ISSUE THREAD

**Issue by scubalaina** [dutilh/CAT#7]
Hi there,

I have used CAT in the past, and it has worked perfectly. Unfortunately, this time, my output files are empty, despite numerous tries and re-running the preparation steps (i.e. making the blast database, running the blastp). The object file that appears only says:

`Parsing diamond alignment`
`Parsing prot.accession2taxid file`
`Computation`
`Let's summarise...`
`-----------------------`

My input blastp database is even formatted with the better headings for CAT (no spaces in labels, tab delimited). For example:

`3C_NODE_166_length_19564_cov_6.887693_8 WP_008679397.1:MULTISPECIES:_bifunctional_(p)ppGpp_synthetase/guanosine-3',5'-bis(diphosphate)_3'-pyrophosphohydrolase  31.3   195      120     5       39      229     23      207     5.7e-14     82.8`

What could be preventing CAT from performing?

Thank you so much for your help!
Alaina :smiley:

**Comment by dutilh** [comment]
Dear Alaina,
* Which version of CAT did you use? You can find this at the head of the script.
* Which command did you use to run?
* If possible, can you send the alignment file?
Best! Bas

**Comment by scubalaina** [comment]
Dear Bas,

Thank you so much for your help!


*Which version of CAT did you use? You can find this at the head of the
script. *
 It is CAT version 2.0, downloaded on Dec 1, 2017

*Which command did you use to run? *
#PBS -N CAT_on_uncertain_vcs_rd6
#PBS -m bea
#PBS -M alainarw94@gmail.com
#PBS -j oe

#PBS -l nodes=1:ppn=14
#PBS -l mem=56GB
#PBS -l walltime=100:0:0

cd /fs/project/PAS1117/Alaina/01_Bathy_virome/uncertain_CAT_again
module load python/3.5
/fs/project/PAS1117/bioinformatic_tools/CAT/CAT -d
Uncertain_new_vcs_blastp_result --prefix Uncertain_CAT


*If possible, can you send the alignment file?*
Sure! I'll attach it. :)

Thank you so, so much!

Have a great day!

Thanks,
Alaina :)

**Comment by dutilh** [comment]
Hi Alaina, it seems that CAT finished smoothly since the alignment file looks fine. Is it possible that the databases don’t match? So does the prot2taxid (or nucl2taxid) file match with the protein database (i.e. were they downloaded on the same date)? Otherwise there may be accessions in the database that are not linked to a taxID. ftp://ftp.ncbi.nih.gov/pub/taxonomy/ Bas

**Comment by bastiaanvonmeijenfeldt** [comment]
Closed this thread because CAT has been rewritten from scratch.
