### ISSUE TITLE
version update request

### ISSUE THREAD

**Issue by AstrobioMike** [dutilh/CAT#79]
Hiya :)

I was elated to see you built in functionality for using GTDB, thanks!

Can you please update the released version so that it includes the new functionality? This will help people trying to install and use it, and will also allow things to be updated in conda. 

Thanks!

**Comment by AstrobioMike** [comment]
Just adding a note here, after pulling the code base to work with GTDB, i realize some things need to be updated first: https://github.com/dutilh/CAT/pull/80

**Comment by bastiaanvonmeijenfeldt** [comment]
Hello! The latest release includes GTDB, and we're close to updating to 6.0 which includes Read Annotation Tool (RAT) as well! Thanks for keeping us sharp!

Best wishes,

Bastiaan
