### ISSUE TITLE
diamond takes all available threads

### ISSUE THREAD

**Issue by noriko-cassman** [dutilh/CAT#9]
Hi guys, 

I noticed while running CAT that during the diamond step it uses all available threads. It would be great to be able to specify this instead of having all run as default.

Nori

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Nori,

The latest version of CAT allows for a '-n' flag that specifies the number of cores to be deployed by Diamond. Hope this helps!

Bastiaan
